config/routes.rb
Iqf::Application.routes.draw do
  resources :posts do
    resources :comments
  end

  get "home/index"

root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author, :content, :destination, :discipline, :project, :subject, :tag, :tags_attributes

  validates :project,  :presence => true,
                    :length => { :minimum => 3 }
  validates :author,  :presence => true,
                    :length => { :minimum => 3 }
  validates :destination, :presence => true,
                    :length => { :minimum => 3 }
  validates :discipline,  :presence => true,
                    :length => { :minimum => 3 }
  validates :tag,  :presence => true,
                    :length => { :minimum => 24 } 
  validates :subject,  :presence => true,
                    :length => { :minimum => 5 }
  validates :content, :presence => true,
                    :length => { :minimum => 10 }

  has_many :comments, :dependent => :destroy
    has_many :tags

    accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
#  http_basic_authenticate_with :name => "admin", :password => "secret", :only => :destroy
 
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  # http_basic_authenticate_with :name => "user", :password => "secret", :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'IQF was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'IQF was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
 
<p>
  <%= link_to 'Delete Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Interface Management System</h1>
<%= link_to "IQF", posts_path %>
<p>® ECOVIX - Todos os direitos reservados.<p>
<%# <p>Find me in app/views/home/index.html.erb</p> %>
<%# This is a great comment! %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECOVIX - Interface Management System</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #EEEEEE;">
 
<%= yield %>
 
</body>
</html>

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this IQF from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= post_form.label :project %><br />
    <%= post_form.select(:project, [['CASSINO', '009'], ['CURUMIM', '010'], ['SALINAS', '011']]) %>
  </div>
  <div class="field">
    <%= post_form.label :author %><br />
    <%= post_form.select(:author, [['ECOVIX', 'OVX'], ['COSCO', 'COS'], ['HBR', 'HKQ'], ['VICTOR MARINE', 'VC8'], ['HEINEM HOPMAN', 'HEI'], ['HUISMAN', 'HCG'], ['NOV', 'ND1'], ['ALFA NAVAL', 'LIM'], ['GEA', 'GBR'], ['WARTSILA', 'WNF'], ['GE', 'GC1']]) %>
  </div>
  <div class="field">
    <%= post_form.label :destination %><br />
    <%= post_form.select(:destination, [['ECOVIX', 'OVX'], ['COSCO', 'COS'], ['HBR', 'HKQ'], ['VICTOR MARINE', 'VC8'], ['HEINEM HOPMAN', 'HEI'], ['HUISMAN', 'HCG'], ['NOV', 'ND1'], ['ALFA NAVAL', 'LIM'], ['GEA', 'GBR'], ['WARTSILA', 'WNF'], ['GE', 'GC1']]) %>
  </div>
  <div class="field">
    <%= post_form.label :discipline %><br />
    <%= post_form.select(:discipline, [['GENERAL', 'GEN'], ['HULL STRUCTURE', 'HST'], ['OUTFITTING', 'OUT'], ['ARCHITECTURE', 'ARC'], ['MARINE MACHINERY', 'MMA'], ['DRILLING MACHINERY', 'DMA'], ['MARINE PIPING', 'MPI'], ['HVAC', 'HVA'], ['DRILLING PIPING', 'DPI'], ['ELECTRICAL POWER', 'EPO'], ['INSTRUMENT', 'INS'], ['COMMUNICATION', 'COM']]) %>
  </div>
  <div class="field">
    <%= post_form.label :IQF_number %><br />
    <%= post_form.text_field :tag %>
  </div>
  <div class="field">
    <%= post_form.label :subject %><br />
    <%= post_form.text_field :subject %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content %>
  </div>
  <h2>Status</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
  <div class="actions">
    <%= post_form.submit "Create IQF"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing IQF</h1>

<%= render 'form' %>

<%= link_to 'View IQF', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing IQF's</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Author</th>
    <th>Destination</th>
    <th>Discipline</th>
    <th>IQF Number</th>
    <th>Subject</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.project %></td>
    <td><%= post.author %></td>
    <td><%= post.destination %></td>
    <td><%= post.discipline %></td>
    <td><%= post.tag %></td>
    <td><%= post.subject %></td>

    <td><%= link_to 'View / Add a Comment', post %></td>
    <td><%= link_to 'Edit IQF', edit_post_path(post) %></td>
    <td><%= link_to 'Delete IQF', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New IQF', new_post_path %>
<%= link_to 'Back', home_index_path %>

app/views/posts/new.html.erb
<h1>New IQF</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>View / Add a Comment to IQF</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @post.project %>
</p>

<p>
  <b>Author:</b>
  <%= @post.author %>
</p>

<p>
  <b>Destination:</b>
  <%= @post.destination %>
</p>

<p>
  <b>Discipline:</b>
  <%= @post.discipline %>
</p>

<p>
  <b>IQF Number:</b>
  <%= @post.tag %>
</p>

<p>
  <b>Subject:</b>
  <%= @post.subject %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Status:</b>
  <%= join_tags(@post) %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Back', posts_path %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Status:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>